version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.x
            
    pre_build:
        commands:
            - chmod +x build-image.sh push-image.sh
            - ./build-image.sh
    build:
        commands:
            - ./push-image.sh
    post_build:
        commands:
          - printf '[{"name":"aveevacontosonoseed","imageUri":"%s"}]' 127275507218.dkr.ecr.us-east-1.amazonaws.com/contosouniversity:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json