version: '3.4'


services:
  contosouniversity.web:
    container_name: contoso-app
    image: ${DOCKER_REGISTRY-}contosouniversityweb
    build:
      context: .
      dockerfile: ContosoUniversity.Web/Dockerfile
   

  
